---
kind: pipeline
type: docker
name: default

steps:
  - name: clone-repository
    image: alpine/git
    environment:
      GIT_DEPTH: "1"
    commands:
      - git clone https://${DRONE_GITHUB_USERNAME}:${DRONE_GITHUB_TOKEN}@github.com/DivineTaminang2/drone-project.git ./repo

  - name: print-message
    image: alpine:latest
    commands:
      - echo "Hello, Drone CI! This is a simple pipeline. Thank you all very much !!!"


